# Generated by Django 4.2 on 2023-04-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0002_remove_family_children_family_first_child_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cows", models.IntegerField(blank=True, null=True)),
                ("sheeps", models.IntegerField(blank=True, null=True)),
                ("goats", models.IntegerField(blank=True, null=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP.family"
                    ),
                ),
            ],
        ),
    ]
