# Generated by Django 4.2 on 2023-04-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0003_animals"),
    ]

    operations = [
        migrations.CreateModel(
            name="child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(default="XYZ", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="cow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cow_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="goat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goat_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="sheap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheap_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="family",
            name="First_child",
        ),
        migrations.RemoveField(
            model_name="family",
            name="Second_child",
        ),
        migrations.RemoveField(
            model_name="family",
            name="Third_child",
        ),
        migrations.AddField(
            model_name="family",
            name="children",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="cows",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="family",
            name="goats",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="sheaps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="animals",
        ),
        migrations.AddField(
            model_name="sheap",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APP.family"
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APP.family"
            ),
        ),
        migrations.AddField(
            model_name="cow",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APP.family"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="Parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APP.family"
            ),
        ),
    ]
