# Generated by Django 4.2 on 2023-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0004_child_cow_goat_sheap_remove_family_first_child_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goat",
            name="goat_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sheap",
            name="sheap_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
