# Generated by Django 4.2 on 2023-04-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0005_alter_goat_goat_name_alter_sheap_sheap_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="Parent",
        ),
        migrations.RemoveField(
            model_name="cow",
            name="farmer",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="farmer",
        ),
        migrations.RemoveField(
            model_name="sheap",
            name="farmer",
        ),
        migrations.AddField(
            model_name="family",
            name="child_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_names",
                to="APP.child",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="cow_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cow_names",
                to="APP.cow",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="goat_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goat_names",
                to="APP.goat",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="sheap_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheap_names",
                to="APP.sheap",
            ),
        ),
    ]
