# Generated by Django 4.2 on 2023-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0008_alter_child_child_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="child_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cow",
            name="cow_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
