# Generated by Django 4.2 on 2023-04-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0009_alter_child_child_name_alter_cow_cow_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="child_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name_child",
                to="APP.child",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="cow_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name_cow",
                to="APP.cow",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="goat_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name_goat",
                to="APP.goat",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="sheap_names",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name_sheap",
                to="APP.sheap",
            ),
        ),
    ]
